# Example configuration for Approval Hook System

# Mount the approval hook
[[hooks]]
module = "hooks-approval"

# Approval hook configuration
[hooks.approval]
# Action to take when approval times out or provider fails
# Options: "deny" (safe default), "continue" (allow operation)
default_action = "deny"

# Audit trail configuration
[hooks.approval.audit]
# Enable audit logging of all approval decisions
enabled = true
# Path to audit log file (JSONL format)
file = "~/.amplifier/audit/approvals.jsonl"

# Auto-approval rules (optional)
# Rules are evaluated in order, first match wins

# Example: Auto-approve safe read-only commands
[[hooks.approval.rules]]
pattern = "ls*"
action = "auto_approve"

[[hooks.approval.rules]]
pattern = "pwd"
action = "auto_approve"

[[hooks.approval.rules]]
pattern = "cat *"
action = "auto_approve"

# Example: Auto-deny dangerous commands
[[hooks.approval.rules]]
pattern = "rm -rf /*"
action = "auto_deny"

[[hooks.approval.rules]]
pattern = "sudo rm*"
action = "auto_deny"

[[hooks.approval.rules]]
pattern = "dd if=/dev/zero*"
action = "auto_deny"

# Example: Require approval for high-risk tools
[[hooks.approval.rules]]
tool = "bash"
risk_level = "high"
require_approval = true

# Example: CI/CD configuration with timeout
# [hooks.approval]
# default_action = "deny"
# timeout = 300  # Fail after 5 minutes in unattended scenarios

# Example: Headless/batch processing (no approval)
# [hooks.approval]
# default_action = "continue"  # Auto-approve everything (use with caution!)
